In [ ]:
print("Hello World!")

# Importing Libraries

In [ ]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data preProcessing

### Training Image Preprocessing

In [15]:

training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
   
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [16]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    
)

Found 17572 files belonging to 38 classes.


In [17]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [18]:
for x,y in training_set:
    # x is training set and y is label
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 71.    66.    64.25]
   [131.   126.   123.  ]
   [119.5  114.5  111.5 ]
   ...
   [108.5  101.5   91.5 ]
   [109.5  102.5   92.5 ]
   [111.25 104.25  94.25]]

  [[ 66.25  61.75  60.25]
   [124.75 119.75 116.75]
   [121.   116.   113.  ]
   ...
   [110.   103.    93.  ]
   [110.5  103.5   93.5 ]
   [110.5  103.5   93.5 ]]

  [[ 66.75  62.25  60.75]
   [126.75 121.75 118.75]
   [128.25 123.25 120.25]
   ...
   [112.   105.    95.  ]
   [111.75 104.75  94.75]
   [109.5  102.5   92.5 ]]

  ...

  [[ 53.5   49.    47.5 ]
   [106.25 101.25  98.25]
   [110.5  105.5  102.5 ]
   ...
   [133.5  127.5  129.5 ]
   [133.5  127.5  129.5 ]
   [136.5  130.5  132.5 ]]

  [[ 56.75  52.    50.5 ]
   [115.75 110.75 107.75]
   [111.5  106.5  103.5 ]
   ...
   [133.   127.   129.  ]
   [132.   126.   128.  ]
   [136.5  130.5  132.5 ]]

  [[ 56.5   52.    50.5 ]
   [113.25 108.25 105.25]
   [105.25 100.25  97.25]
   ...
   [133.5  127.5  129.5 ]
   [130.25 124.25 126.25]
   [134.25 128.25 13

### Building Model

In [ ]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten,Dropout
from tensorflow.keras.models import Sequential


In [72]:
model = Sequential()

In [73]:
## Building convolution layer

In [74]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))


In [75]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [76]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [77]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [ ]:
model.add(Dropout(0.25))  # To avoid Overfitting

In [78]:
model.add(Flatten())

In [79]:
model.add(Dense(units=1500,activation='relu'))

In [ ]:
model.add(Dropout(0.4))

In [80]:
#output layer

model.add(Dense(units=38,activation='softmax'))

### Compiling Model

In [81]:
model.compile(optimizer=tf.keras.optimizers.legacy.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [82]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_34 (Conv2D)          (None, 128, 128, 32)      896       
                                                                 
 conv2d_35 (Conv2D)          (None, 128, 128, 32)      9248      
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 64, 64, 32)       0         
 2D)                                                             
                                                                 
 conv2d_36 (Conv2D)          (None, 64, 64, 64)        18496     
                                                                 
 conv2d_37 (Conv2D)          (None, 64, 64, 64)        36928     
                                                                 
 max_pooling2d_9 (MaxPooling  (None, 32, 32, 64)       0         
 2D)                                                  

### Model Training

In [ ]:
training_history = model.fit(x = training_set,validation_data = validation_set,epochs=10)