In [2]:
print("Hello World!")

Hello World!


# Importing Libraries

In [4]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data preProcessing

### Training Image Preprocessing

In [8]:

training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
   
)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [9]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    
)

Found 17572 files belonging to 38 classes.


In [10]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [12]:
for x,y in training_set:
    # x is training set and y is label
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 92.    87.25  85.  ]
   [ 88.25  83.75  82.25]
   [ 91.75  87.    85.25]
   ...
   [ 68.5   60.    59.5 ]
   [ 69.5   60.25  59.5 ]
   [ 68.25  59.    58.25]]

  [[182.   177.   174.  ]
   [174.   169.   166.  ]
   [180.75 175.75 172.75]
   ...
   [133.5  123.5  122.5 ]
   [122.75 112.75 111.75]
   [126.5  116.5  115.5 ]]

  [[185.5  180.5  177.5 ]
   [174.75 169.75 166.75]
   [176.75 171.75 168.75]
   ...
   [139.25 129.25 128.25]
   [125.75 115.75 114.75]
   [131.   121.   120.  ]]

  ...

  [[194.75 189.75 193.75]
   [198.5  193.5  197.5 ]
   [193.   188.   192.  ]
   ...
   [138.   127.   131.  ]
   [134.75 123.75 127.75]
   [136.75 125.75 129.75]]

  [[191.   186.   190.  ]
   [199.75 194.75 198.75]
   [193.5  188.5  192.5 ]
   ...
   [137.75 126.75 130.75]
   [133.75 122.75 126.75]
   [134.   123.   127.  ]]

  [[195.75 190.75 194.75]
   [195.25 190.25 194.25]
   [186.5  181.5  185.5 ]
   ...
   [135.25 124.25 128.25]
   [131.5  120.5  124.5 ]
   [137.5  126.5  13