In [1]:
print("Hello World!")

Hello World!


In [2]:
import tensorflow as tf
tf.test.gpu_device_name()

''

# Importing Libraries

In [3]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data preProcessing

### Training Image Preprocessing

In [4]:

training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

Found 70295 files belonging to 38 classes.


### Validation Image Preprocessing

In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

Found 17572 files belonging to 38 classes.


In [6]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [7]:
for x,y in training_set:
    # x is training set and y is label
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[ 69.75  60.25  64.75]
   [135.5  122.5  129.5 ]
   [145.5  128.5  136.5 ]
   ...
   [146.75 133.75 142.75]
   [143.5  130.5  139.5 ]
   [130.25 117.25 126.25]]

  [[ 73.5   63.5   68.5 ]
   [133.   120.   127.  ]
   [137.5  120.5  128.5 ]
   ...
   [133.5  120.5  129.5 ]
   [156.25 143.25 152.25]
   [142.   129.   138.  ]]

  [[ 69.75  60.25  64.75]
   [136.5  123.5  130.5 ]
   [138.   121.   129.  ]
   ...
   [154.25 141.25 150.25]
   [170.   157.   166.  ]
   [161.5  148.5  157.5 ]]

  ...

  [[ 80.5   70.75  73.5 ]
   [149.5  137.5  141.5 ]
   [157.25 140.25 146.25]
   ...
   [174.5  159.5  166.5 ]
   [173.   158.   165.  ]
   [185.   170.   177.  ]]

  [[ 83.75  73.75  76.75]
   [137.5  125.5  129.5 ]
   [148.25 131.25 137.25]
   ...
   [180.25 165.25 172.25]
   [178.25 163.25 170.25]
   [160.75 145.75 152.75]]

  [[ 73.25  63.25  66.25]
   [142.25 130.25 134.25]
   [129.5  112.5  118.5 ]
   ...
   [160.75 145.75 152.75]
   [156.25 141.25 148.25]
   [182.75 167.75 17

### Building Model

In [8]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten,Dropout
from tensorflow.keras.models import Sequential


In [9]:
model = Sequential()

In [10]:
## Building convolution layer

In [11]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))


In [12]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [14]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [15]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [16]:
model.add(Dropout(0.25))  # To avoid Overfitting

In [17]:
model.add(Flatten())

In [18]:
model.add(Dense(units=1500,activation='relu'))

In [19]:
model.add(Dropout(0.4))

In [20]:
#output layer

model.add(Dense(units=38,activation='softmax'))

### Compiling Model

In [21]:
model.compile(optimizer=tf.keras.optimizers.legacy.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 63, 63, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                    

### Model Training

In [ ]:
training_history = model.fit(x = training_set,validation_data = validation_set,epochs=10)

### Model Evalution

In [ ]:
# Model Evalution on traning set
train_loss, train_acc = model.evaluate(training_set)


In [ ]:
print('Training accuracy:', train_acc)
print('Training Loss:', train_loss)

In [ ]:
# Model on validation set
val_loss, val_acc = cnn.evaluate(validation_set)


In [ ]:
print('Validation accuracy:', val_acc)
print('Validation loss:', val_loss)

### Saving Model

In [ ]:
model.save('trained_model.keras')

In [ ]:
# model.save('trained_model.h5')

In [ ]:
training_history.history #Return Dictionary of history

In [ ]:
#Recording History in json
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

In [ ]:
print(training_history.history.keys())

### Accuracy Visulization

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel('No. of Epochs')
plt.title('Visualization of Accuracy Result')
plt.legend()
plt.show()

### Classification (othor model)

In [ ]:
class_name = validation_set.class_names

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

# Predictions.

In [ ]:
y_pred = model.predict(test_set)
predicted_categories = tf.argmax(y_pred, axis=1)

In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis=0)
Y_true = tf.argmax(true_categories, axis=1)

In [ ]:
Y_true

In [ ]:
predicted_categories

### Classification Report

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
# Precision Recall Fscore
print(classification_report(Y_true,predicted_categories,target_names=class_name))

In [ ]:
# Precision =(TP/(TP+FP))
# Recall =(TP/(TP+FN))
# Accuracy =((TP+TN)/(TP+TN+FP+FN))
# f1-score = Harmonic mean of Precision and Recall

In [ ]:
# pred = model.predict(testds)
# pred = [np.argmax(i) for i in pred]
# y_test = testds.classes
# print(classification_report(pred,y_test))

### Confusion Matrix

In [ ]:
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
cm

In [ ]:
cm.shape

In [ ]:
plt.figure(figsize=(40, 40))
sns.heatmap(cm,annot=True,annot_kws={"size": 10})

plt.xlabel('Predicted Class',fontsize = 20)
plt.ylabel('Actual Class',fontsize = 20)
plt.title('Plant Disease Prediction Confusion Matrix',fontsize = 25)
plt.show()