<a href="https://colab.research.google.com/github/nishantkr2003/Plant-Disease-Detection/blob/main/Train_Plant_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World!")

Hello World!


In [2]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

# Importing Libraries

In [3]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
!git clone https://github.com/nishantkr2003/Plant-Disease-Detection.git

Cloning into 'Plant-Disease-Detection'...
remote: Enumerating objects: 87957, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 87957 (delta 14), reused 19 (delta 6), pack-reused 87927 (from 2)
Receiving objects: 100% (87957/87957), 1.31 GiB | 31.04 MiB/s, done.
Resolving deltas: 100% (32/32), done.
Updating files: 100% (87905/87905), done.


In [22]:
!ls Plant-Disease-Detection


README.md  requirement.txt  test  train  Train_Plant_disease.ipynb  valid


# Data preProcessing

### Training Image Preprocessing

In [24]:

training_set = tf.keras.utils.image_dataset_from_directory(
    "/content/Plant-Disease-Detection/train",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)
print("Dataset successfully loaded!")

Found 70295 files belonging to 38 classes.
Dataset successfully loaded!


### Validation Image Preprocessing

In [25]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    "/content/Plant-Disease-Detection/valid",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)


print("Validation dataset successfully loaded!")

Found 17572 files belonging to 38 classes.
Validation dataset successfully loaded!


In [26]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [27]:
for x,y in training_set:
    # x is training set and y is label
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[195.   191.   205.  ]
   [185.25 181.25 195.25]
   [182.75 178.75 192.75]
   ...
   [159.25 153.25 165.25]
   [174.5  168.5  180.5 ]
   [163.75 157.75 169.75]]

  [[191.75 187.75 201.75]
   [190.25 186.25 200.25]
   [187.25 183.25 197.25]
   ...
   [174.75 168.75 180.75]
   [167.5  161.5  173.5 ]
   [185.75 179.75 191.75]]

  [[190.   186.   200.  ]
   [184.75 180.75 194.75]
   [194.   190.   204.  ]
   ...
   [180.75 174.75 186.75]
   [175.25 169.25 181.25]
   [171.5  165.5  177.5 ]]

  ...

  [[176.75 172.75 186.75]
   [177.25 173.25 187.25]
   [181.5  177.5  191.5 ]
   ...
   [148.75 142.75 154.75]
   [143.75 137.75 149.75]
   [152.5  146.5  158.5 ]]

  [[181.25 177.25 191.25]
   [176.75 172.75 186.75]
   [178.75 174.75 188.75]
   ...
   [150.5  144.5  156.5 ]
   [151.25 145.25 157.25]
   [153.25 147.25 159.25]]

  [[187.75 183.75 197.75]
   [180.5  176.5  190.5 ]
   [182.25 178.25 192.25]
   ...
   [141.5  135.5  147.5 ]
   [150.75 144.75 156.75]
   [159.75 153.75 16

### Building Model

In [43]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D, Flatten,Dropout
from tensorflow.keras.models import Sequential


In [44]:
model = Sequential()

In [45]:
## Building convolution layer

In [46]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))


In [47]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [48]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [49]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [52]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [53]:
model.add(Dropout(0.25))  # To avoid Overfitting

In [54]:
model.add(Flatten())

In [55]:
model.add(Dense(units=1500,activation='relu'))

In [56]:
model.add(Dropout(0.4))

In [57]:
#output layer

model.add(Dense(units=38,activation='softmax'))

In [ ]:
#model.compile(optimizer=tf.keras.optimizers.legacy.Adam(
#   learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [59]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

### Compiling Model

In [60]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_12 (Conv2D)                   │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_13 (Conv2D)                   │ (None, 126, 126, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_6 (MaxPooling2D)       │ (None, 63, 63, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_14 (Conv2D)                   │ (None, 63, 63, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_15 (Conv2D)                   │ (None, 61, 61, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_7 (MaxPooling2D)       │ (None, 30, 30, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_16 (Conv2D)                   │ (None, 30, 30, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_17 (Conv2D)                   │ (None, 28, 28, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_8 (MaxPooling2D)       │ (None, 14, 14, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_18 (Conv2D)                   │ (None, 14, 14, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_19 (Conv2D)                   │ (None, 12, 12, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_9 (MaxPooling2D)       │ (None, 6, 6, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_20 (Conv2D)                   │ (None, 6, 6, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_21 (Conv2D)                   │ (None, 4, 4, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_10 (MaxPooling2D)      │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 2, 2, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_22 (Conv2D)                   │ (None, 2, 2, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_23 (Conv2D)                   │ (None, 0, 0, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_11 (MaxPooling2D)      │ (None, 0, 0, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 0, 0, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 0)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼──────────────

 Total params: 9,490,378 (36.20 MB)

 Trainable params: 9,490,378 (36.20 MB)

 Non-trainable params: 0 (0.00 B)

### Model Training

In [ ]:
training_history = model.fit(x = training_set,validation_data = validation_set,epochs=10)

### Model Evalution

In [ ]:
# Model Evalution on traning set
train_loss, train_acc = model.evaluate(training_set)


In [ ]:
print('Training accuracy:', train_acc)
print('Training Loss:', train_loss)

In [ ]:
# Model on validation set
val_loss, val_acc = cnn.evaluate(validation_set)


In [ ]:
print('Validation accuracy:', val_acc)
print('Validation loss:', val_loss)

### Saving Model

In [ ]:
model.save('trained_model.keras')

In [ ]:
# model.save('trained_model.h5')

In [ ]:
training_history.history #Return Dictionary of history

In [ ]:
#Recording History in json
import json
with open('training_hist.json','w') as f:
  json.dump(training_history.history,f)

In [ ]:
print(training_history.history.keys())

### Accuracy Visulization

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs,training_history.history['accuracy'],color='red',label='Training Accuracy')
plt.plot(epochs,training_history.history['val_accuracy'],color='blue',label='Validation Accuracy')
plt.xlabel('No. of Epochs')
plt.title('Visualization of Accuracy Result')
plt.legend()
plt.show()

### Classification (othor model)

In [ ]:
class_name = validation_set.class_names

In [ ]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=1,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

# Predictions.

In [ ]:
y_pred = model.predict(test_set)
predicted_categories = tf.argmax(y_pred, axis=1)

In [ ]:
true_categories = tf.concat([y for x, y in test_set], axis=0)
Y_true = tf.argmax(true_categories, axis=1)

In [ ]:
Y_true

In [ ]:
predicted_categories

### Classification Report

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
# Precision Recall Fscore
print(classification_report(Y_true,predicted_categories,target_names=class_name))

In [ ]:
# Precision =(TP/(TP+FP))
# Recall =(TP/(TP+FN))
# Accuracy =((TP+TN)/(TP+TN+FP+FN))
# f1-score = Harmonic mean of Precision and Recall

In [ ]:
# pred = model.predict(testds)
# pred = [np.argmax(i) for i in pred]
# y_test = testds.classes
# print(classification_report(pred,y_test))

### Confusion Matrix

In [ ]:
cm = confusion_matrix(Y_true,predicted_categories)

In [ ]:
cm

In [ ]:
cm.shape

In [ ]:
plt.figure(figsize=(40, 40))
sns.heatmap(cm,annot=True,annot_kws={"size": 10})

plt.xlabel('Predicted Class',fontsize = 20)
plt.ylabel('Actual Class',fontsize = 20)
plt.title('Plant Disease Prediction Confusion Matrix',fontsize = 25)
plt.show()